#!/usr/bin/env python3
# Copyright (C) 2026 The media3-decoder-ape Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Generates the extended APE test corpus (TZ section 4.2).

Every generated file is produced from the reference WAV by the official
MAC 13.20 console tool and immediately verified by decoding it back and
comparing the data-chunk MD5 with the source WAV, making the corpus
self-checking. The results and their expected PCM MD5s are written to
manifest.csv in the output directory, in the format consumed by
ApeExtractorInstrumentationTest.

Usage:
  python generate_corpus.py <reference.wav> <output_dir> [options]
  python generate_corpus.py --synth SECONDS <output_dir> [options]

With --synth the reference WAV is generated by ffmpeg (a deterministic-shape
sweep plus noise), so no external audio is needed at all.

Options:
  --mac PATH      MAC console encoder (default: $MAC_CONSOLE, then "mac" on PATH)
  --long          also produce the ~80-minute single-image file
  --ref-pcm NAME  write the reference data chunk as NAME and mark every output
                  that decodes to it, enabling the seek tests on this corpus

Requires: ffmpeg on PATH and the official MAC console tool (13.20), built
from the SDK fetched by src/main/jni/download_maclib.sh.
"""

import hashlib
import os
import shutil
import struct
import subprocess
import sys


def find_mac(explicit):
    if explicit:
        return explicit
    if os.environ.get("MAC_CONSOLE"):
        return os.environ["MAC_CONSOLE"]
    found = shutil.which("mac") or shutil.which("mac_console")
    if not found:
        sys.exit("MAC console encoder not found: pass --mac, set MAC_CONSOLE, "
                 "or put mac/mac_console on PATH")
    return found


MAC = None  # set in main()


def run(args):
    result = subprocess.run(args, capture_output=True)
    if result.returncode != 0:
        raise RuntimeError(
            "command failed (%d): %s\n%s" % (result.returncode, args, result.stderr[:2000]))


def wav_data_md5(path):
    """MD5 of the data chunk contents (RIFF-parsed, not offset-assumed)."""
    with open(path, 'rb') as f:
        riff = f.read(12)
        assert riff[0:4] == b'RIFF' and riff[8:12] == b'WAVE', path
        while True:
            header = f.read(8)
            if len(header) < 8:
                raise RuntimeError("no data chunk in " + path)
            chunk_id, size = header[0:4], struct.unpack('<I', header[4:8])[0]
            if chunk_id == b'data':
                md5 = hashlib.md5()
                remaining = size
                while remaining > 0:
                    block = f.read(min(1 << 20, remaining))
                    if not block:
                        break
                    md5.update(block)
                    remaining -= len(block)
                return md5.hexdigest().upper(), size
            f.seek(size + (size & 1), os.SEEK_CUR)


def total_blocks(pcm_bytes, channels, bits):
    return pcm_bytes // (channels * bits // 8)


class Corpus:
    def __init__(self, out_dir):
        self.out_dir = out_dir
        self.manifest = []
        self.broken = []

    def compress_and_verify(self, wav_path, ape_name, level, channels, bits, ref_name=None):
        """Compresses wav -> ape, decodes back, verifies bit-exactness."""
        ape_path = os.path.join(self.out_dir, ape_name)
        run([MAC, wav_path, ape_path, "-c%d" % level])

        source_md5, source_bytes = wav_data_md5(wav_path)

        check_wav = ape_path + ".check.wav"
        run([MAC, ape_path, check_wav, "-d"])
        check_md5, check_bytes = wav_data_md5(check_wav)
        os.remove(check_wav)
        if check_md5 != source_md5 or check_bytes != source_bytes:
            raise RuntimeError("round-trip mismatch for " + ape_name)

        blocks = total_blocks(source_bytes, channels, bits)
        self.manifest.append((ape_name, source_md5, blocks, ref_name or ""))
        print("OK  %-40s %s blocks=%d" % (ape_name, source_md5, blocks))
        return ape_path

    def add_existing(self, ape_path, md5, blocks, ref_name=""):
        name = os.path.basename(ape_path)
        self.manifest.append((name, md5, blocks, ref_name))

    def write(self):
        with open(os.path.join(self.out_dir, "manifest.csv"), "w") as f:
            f.write("# filename,expected_pcm_md5,expected_blocks,reference_pcm\n")
            for name, md5, blocks, ref in self.manifest:
                f.write("%s,%s,%d,%s\n" % (name, md5, blocks, ref))
        with open(os.path.join(self.out_dir, "broken.txt"), "w") as f:
            for name in self.broken:
                f.write(name + "\n")


def make_ape_tag(items):
    """Builds an APEv2 tag (header + items + footer)."""
    body = b""
    for key, value, is_binary in items:
        flags = 2 if is_binary else 0
        data = value if is_binary else value.encode("utf-8")
        body += struct.pack("<II", len(data), flags) + key.encode("utf-8") + b"\0" + data
    size = len(body) + 32
    count = len(items)

    def block(is_header):
        flags = 0xA0000000 if is_header else 0x80000000
        return (b"APETAGEX" + struct.pack("<IIII", 2000, size, count, flags) + b"\0" * 8)

    return block(True) + body + block(False)


def make_id3v1(title, artist, album, year, track):
    tag = bytearray(128)
    tag[0:3] = b"TAG"
    tag[3:3 + len(title)] = title.encode("ascii")
    tag[33:33 + len(artist)] = artist.encode("ascii")
    tag[63:63 + len(album)] = album.encode("ascii")
    tag[93:97] = year.encode("ascii")
    tag[125] = 0
    tag[126] = track
    tag[127] = 17  # genre: Rock
    return bytes(tag)


def make_png():
    """A tiny valid 1x1 red PNG."""
    return bytes.fromhex(
        "89504e470d0a1a0a0000000d49484452000000010000000108020000009077"
        "53de0000000c4944415408d763f8cfc000000301010018dd8db00000000049"
        "454e44ae426082")


def main():
    global MAC
    args = sys.argv[1:]

    def take_option(name, has_value=True):
        if name not in args:
            return None
        i = args.index(name)
        args.pop(i)
        return args.pop(i) if has_value else True

    MAC = find_mac(take_option("--mac"))
    want_long = bool(take_option("--long", has_value=False))
    ref_pcm_name = take_option("--ref-pcm")
    synth_seconds = take_option("--synth")

    out_dir = args[-1]
    os.makedirs(out_dir, exist_ok=True)
    tmp = os.path.join(out_dir, "_tmp")
    os.makedirs(tmp, exist_ok=True)

    if synth_seconds is not None:
        # Two dissimilar channels: sweeps against noise beds, so every level has
        # real work to do and stereo decorrelation is exercised.
        ref_wav = os.path.join(tmp, "ref.wav")
        expr = ("sin(2*PI*(200+400*t)*t)*0.6+(random(0)-0.5)*0.12|"
                "cos(2*PI*(320+250*t)*t)*0.6+(random(1)-0.5)*0.12")
        run(["ffmpeg", "-y", "-loglevel", "error",
             "-f", "lavfi", "-i",
             "aevalsrc=%s:s=44100:d=%s" % (expr, synth_seconds),
             "-c:a", "pcm_s16le", ref_wav])
    else:
        ref_wav = args[0]

    corpus = Corpus(out_dir)

    def ffmpeg(out_name, *args):
        out = os.path.join(tmp, out_name)
        run(["ffmpeg", "-y", "-loglevel", "error", "-i", ref_wav] + list(args) + [out])
        return out

    # --- compression levels on the untouched reference (Normal is produced by
    # generate_ci_corpus.py from the longer program, so it is absent here) ---
    for level, name in ((5000, "insane"), (1000, "fast"), (3000, "high"),
                        (4000, "extrahigh")):
        corpus.compress_and_verify(ref_wav, "gen-1399-%s-44k-16b-2ch.ape" % name,
                                   level, channels=2, bits=16)

    # --- bit depths ---
    wav = ffmpeg("24bit.wav", "-c:a", "pcm_s24le")
    corpus.compress_and_verify(wav, "gen-1399-normal-44k-24b-2ch.ape", 2000, 2, 24)
    wav = ffmpeg("8bit.wav", "-c:a", "pcm_u8")
    corpus.compress_and_verify(wav, "gen-1399-normal-44k-8b-2ch.ape", 2000, 2, 8)
    wav = ffmpeg("f32.wav", "-c:a", "pcm_f32le")
    corpus.compress_and_verify(wav, "gen-1399-normal-44k-f32-2ch.ape", 2000, 2, 32)

    # --- channel counts ---
    wav = ffmpeg("mono.wav", "-ac", "1")
    corpus.compress_and_verify(wav, "gen-1399-normal-44k-16b-1ch.ape", 2000, 1, 16)
    wav = ffmpeg("51.wav", "-ac", "6")
    corpus.compress_and_verify(wav, "gen-1399-normal-44k-16b-6ch.ape", 2000, 6, 16)

    # --- sample rates ---
    for rate in (48000, 88200, 96000, 192000):
        wav = ffmpeg("r%d.wav" % rate, "-ar", str(rate))
        corpus.compress_and_verify(wav, "gen-1399-normal-%dk-16b-2ch.ape" % (rate // 1000),
                                   2000, 2, 16)

    # --- tags: APEv2 with cover art, ID3v1, both ---
    base = corpus.compress_and_verify(ref_wav, "gen-1399-normal-tagged-apev2.ape", 2000, 2, 16)
    base_entry = corpus.manifest[-1]
    tag = make_ape_tag([
        ("Title", "Reference Track", False),
        ("Artist", "Test Artist", False),
        ("Album", "Corpus", False),
        ("Track", "7", False),
        ("Cover Art (front)", b"cover.png\0" + make_png(), True),
    ])
    with open(base, "ab") as f:
        f.write(tag)
    print("OK  tag appended: apev2+cover")

    shutil.copyfile(base, os.path.join(out_dir, "gen-1399-normal-tagged-both.ape"))
    with open(os.path.join(out_dir, "gen-1399-normal-tagged-both.ape"), "ab") as f:
        f.write(make_id3v1("Reference Track", "Test Artist", "Corpus", "2026", 7))
    corpus.add_existing(os.path.join(out_dir, "gen-1399-normal-tagged-both.ape"),
                        base_entry[1], base_entry[2])

    id3only = corpus.compress_and_verify(ref_wav, "gen-1399-normal-tagged-id3v1.ape", 2000, 2, 16)
    with open(id3only, "ab") as f:
        f.write(make_id3v1("Reference Track", "Test Artist", "Corpus", "2026", 7))

    # --- long file (~80 minutes): the CUE+APE single-image scenario ---
    if want_long:
        concat_list = os.path.join(tmp, "concat.txt")
        with open(concat_list, "w") as f:
            for _ in range(21):
                f.write("file '%s'\n" % os.path.abspath(ref_wav).replace("'", "'\\''"))
        long_wav = os.path.join(tmp, "long.wav")
        run(["ffmpeg", "-y", "-loglevel", "error", "-f", "concat", "-safe", "0",
             "-i", concat_list, "-c", "copy", long_wav])
        corpus.compress_and_verify(long_wav, "gen-1399-high-long80min.ape", 3000, 2, 16)

    # --- deliberately damaged files ---
    donor = corpus.compress_and_verify(ref_wav, "gen-donor.ape", 2000, 2, 16)
    corpus.manifest.pop()  # the donor itself is not part of the corpus

    # bytes corrupted inside frame data
    with open(donor, "rb") as f:
        data = bytearray(f.read())
    for offset in range(len(data) // 2, len(data) // 2 + 32):
        data[offset] ^= 0xFF
    with open(os.path.join(out_dir, "gen-broken-frame-bytes.ape"), "wb") as f:
        f.write(data)
    corpus.broken.append("gen-broken-frame-bytes.ape")

    # truncated: second half cut off
    with open(donor, "rb") as f:
        data = f.read()
    with open(os.path.join(out_dir, "gen-broken-truncated.ape"), "wb") as f:
        f.write(data[: len(data) // 2])
    corpus.broken.append("gen-broken-truncated.ape")

    # header corrupted
    with open(donor, "rb") as f:
        data = bytearray(f.read())
    for offset in range(8, 56):
        data[offset] = 0xFF
    with open(os.path.join(out_dir, "gen-broken-header.ape"), "wb") as f:
        f.write(data)
    corpus.broken.append("gen-broken-header.ape")

    os.remove(donor)

    # --- reference PCM for the seek tests ---
    if ref_pcm_name:
        ref_md5, _ = wav_data_md5(ref_wav)
        with open(ref_wav, 'rb') as f:
            data = f.read()
        offset = 12
        while offset < len(data):
            chunk_id = data[offset:offset + 4]
            size = struct.unpack('<I', data[offset + 4:offset + 8])[0]
            if chunk_id == b'data':
                with open(os.path.join(out_dir, ref_pcm_name), 'wb') as f:
                    f.write(data[offset + 8:offset + 8 + size])
                break
            offset += 8 + size + (size & 1)
        corpus.manifest = [
            (name, md5, blocks, ref_pcm_name if md5 == ref_md5 else ref)
            for name, md5, blocks, ref in corpus.manifest
        ]
        print("reference PCM written: %s" % ref_pcm_name)

    shutil.rmtree(tmp)
    corpus.write()
    print("manifest written: %d files, %d broken" % (len(corpus.manifest), len(corpus.broken)))


if __name__ == "__main__":
    main()
